spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loggether
    username: postgres
    password: post1234
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    properties: 
      hibernate:
        format_sql: true
